let bolean = true;
let numbere=10;
let stringer="win";
let undefinede;
let nullo = null;
console.log(typeof bolean);
console.log(typeof numbere);
console.log(typeof stringer);
console.log(typeof undefinede);
console.log(typeof nullo);